version: 3.0.{build}
configuration: Release
pull_requests:
  do_not_increment_build_number: true
image:
- Visual Studio 2017
- Ubuntu
dotnet_csproj:
  patch: true
  file: '**\Splat.Serilog.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: dotnet restore Source\Splat.Serilog.sln
build:
  project: Source\Splat.Serilog.sln
  publish_nuget: true
  verbosity: minimal
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - ps: dotnet build Source\Splat.Serilog\Splat.Serilog.csproj --framework netstandard2.0